# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d369cc9423e0752335cafe3e58d58dbd23ea16a01ea68ca42b52a688970f86642a7c51059fc7b49a73300a890d68bf1e5be76e27f4a31b95281a570862b95ab7

test:
  secret_key_base: c4c9a01fbbbaad4cb3f2dabbabd29fabcd0702c3a5159406c8e43f107389e5089037f1020df7349c2c24643d4c393c87c8b5ef8675bd178e410d29c4c4d4ce69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
